title: Daniil Sherstnev
description: PhD Candidate Econ USC
theme: minima
markdown: kramdown

repository: dansherstnev/daniil_sherstnev.github.io
url: https://daniil_sherstnev.github.io
baseurl: ""

email: sherstne@usc.edu
linkedin: https://www.linkedin.com/in/daniil-sherstnev-923959232/
location: Los Angeles, California
